version: "3"

services:
  database:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
